### ISSUE TITLE
confidence intervals for brmultinom?

### ISSUE THREAD

**Issue by MelanieCNM** [ikosmidis/brglm2#19]
I am using brmultinom with a small data set (120 cases).  Is there a function or command to find the confidence intervals with the brmultinom function?  I tried using the confint function but it gives no real output or error message.  

All predictors are binary categorical data, except for "Number of Births per Year".  The dependent outcome variable "Financial Sustainability" has 3 categories (best, good, poor)  
###Set working directory 
setwd("C:/Users/Melanie/OneDrive")

###install and library brglm2 package for analysis
install.packages("brglm2")
library(brglm2)

###install and library readxl package to read in data
install.packages("readxl")
library(readxl)

###Read in the data, make the outcome a factor
birthcenter<-read_excel("birthcenterdata")
birthcenter$`Financial Sustainability`<-as.factor(birthcenter$`Financial Sustainability`)
bccomplete<-birthcenter[complete.cases(birthcenter),]

### Model D: uses "1" as baseline to compare "good" to "poor" and "excellent" to "poor."
###Model D shows each estimated coefficient and associated standard errors
modelD <- brmultinom(`Financial Sustainability` ~  `Number of Births per Year` + 
                       `Liability Insurance`+ Accreditation +`Urban/Suburban` + 
                       `For Profit` + `Over 3 years` + 
                       `Licensure Availability`,data=bccomplete,ref=1)
### summarizes the model
summary(modelD)
## Odds ratios
exp(coefficients(modelD))
## confidence intervals
confint(modelD,level = 0.95)
> confint(modelD,level = 0.95)
     2.5 % 97.5 %

Thank you for any / all thoughts + suggestions.

**Comment by ikosmidis** [comment]
Thanks for reporting this. This is just an oversight on my behalf in implementing a `confint` method for `brmultinom`. I will do this in the upcoming version. In the meantime, you can get confidence intervals using the non-exported function from `nnet`:
```r
nnet:::confint.multinom(modelD, level = 0.95)
```

As expected the lower endpoints here (with the default `level = 0.95`) are the same to
```r
sD <- summary(modelD)
sD$coefficients - qnorm(0.975) * sD$standard.errors
```
and the upper to
```r
sD$coefficients + qnorm(0.975) * sD$standard.errors
```

PS: 
1. Just noticed that you send me an email on that, which unfortunately ended up in the wrong directory. Sorry. Here is the right place for these things
2. I could not reproduce your example because I could not access `"birthcenterdata"`. If you find any other issues, perhaps try to produce a minimally reproducible example using the examples in the help files (`?brmultinom` in this case).
