### ISSUE TITLE
Convergence problem

### ISSUE THREAD

**Issue by michalovadek** [ikosmidis/brglm2#29]
Hi, thanks for your work on this package. I am by no means an expert but I tried to read up on penalized logistic regression and encountered several times the claim that in principle Firth regression has better properties when it comes to convergence compared to standard GLM with logit link. I was therefore surprised to see the exact reverse on my data. I was hoping you could help me understand why this happens.

I narrowed down the problem in my regressions to a single variable. I have a longitudinal dataset where I use the year of the observation as a categorical variable, so I get intercepts for each year.

The data is available here: https://github.com/michalovadek/misc/blob/main/data.RDS

```{r}

glm(dv ~ year, data = data, family = binomial()) # converges
glm(dv ~ year, data = data, family = binomial(), method = "brglmFit") # does not converge

```

Any advice would be much appreciated

**Comment by ikosmidis** [comment]
Thanks, for reporting. Yes indeed in http://doi.org/10.1093/biomet/asaa052 we prove that penalized logistic regression produces always finite estimates even if the maximum likelihood estimates have infinite components.

The convergence problems happen rarely but do happen, and are due to the generality of the quasi-Fisher scoring iteration that `brglmFit` implements (trying to cover for all possible glms and model matrices!). In those cases, some tweaking of the iteration (see `?brglm_control`) or supplying better starting values does the trick.

For example, "slowing down" the iteration a bit (using the `slowit` argument; see `?brglm_control`) does the job for your data.

```
glm(dv ~ year, data = data, family = binomial(), method = "brglmFit", slowit = 0.5)
```

**Comment by michalovadek** [comment]
Works, thanks a lot for the help
